name: Python

on: workflow_dispatch

jobs:
  artifact:
    name: Artifact test for the first time 
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > simple-maths.txt
      - name: Upload simple math result
        uses: actions/upload-artifact@v1
        with:
          name: math
          path: simple-maths.txt
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
